/* Generated By:JavaCC: Do not edit this line. EL1ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EL1ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int Digit = 11;
  /** RegularExpression Id. */
  int Letter = 12;
  /** RegularExpression Id. */
  int Num = 13;
  /** RegularExpression Id. */
  int Var = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"fn\"",
    "<Digit>",
    "<Letter>",
    "<Num>",
    "<Var>",
    "\"=>\"",
    "\"+\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
  };

}
