/* Generated By:JavaCC: Do not edit this line. astParserConstants.java */
package ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface astParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int IntLit = 32;
  /** RegularExpression Id. */
  int BoolLit = 33;
  /** RegularExpression Id. */
  int StrLit = 34;
  /** RegularExpression Id. */
  int Digit = 35;
  /** RegularExpression Id. */
  int Letter = 36;
  /** RegularExpression Id. */
  int Id = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT>",
    "\"ArrayElm\"",
    "\"ArrayType\"",
    "\"Assign\"",
    "\"Binop\"",
    "\"BoolType\"",
    "\"Call\"",
    "\"CallStmt\"",
    "\"ClassDecl\"",
    "\"Else\"",
    "\"Field\"",
    "\"Param\"",
    "\"If\"",
    "\"IntType\"",
    "\"MethodDecl\"",
    "\"NewArray\"",
    "\"NewObj\"",
    "\"ObjType\"",
    "\"Print\"",
    "\"Program\"",
    "\"Return\"",
    "\"This\"",
    "\"Unop\"",
    "\"VarDecl\"",
    "\"void\"",
    "\"While\"",
    "<IntLit>",
    "<BoolLit>",
    "<StrLit>",
    "<Digit>",
    "<Letter>",
    "<Id>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!\"",
  };

}
