/* Generated By:JavaCC: Do not edit this line. ast0ParserConstants.java */
package ast0;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ast0ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int kwArrayElm = 7;
  /** RegularExpression Id. */
  int kwAssign = 8;
  /** RegularExpression Id. */
  int kwBinop = 9;
  /** RegularExpression Id. */
  int kwElse = 10;
  /** RegularExpression Id. */
  int kwIf = 11;
  /** RegularExpression Id. */
  int kwNewArray = 12;
  /** RegularExpression Id. */
  int kwPrint = 13;
  /** RegularExpression Id. */
  int kwUnop = 14;
  /** RegularExpression Id. */
  int kwWhile = 15;
  /** RegularExpression Id. */
  int BoolLit = 16;
  /** RegularExpression Id. */
  int Digit = 17;
  /** RegularExpression Id. */
  int Letter = 18;
  /** RegularExpression Id. */
  int IntLit = 19;
  /** RegularExpression Id. */
  int Id = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT>",
    "\"ArrayElm\"",
    "\"Assign\"",
    "\"Binop\"",
    "\"Else\"",
    "\"If\"",
    "\"NewArray\"",
    "\"Print\"",
    "\"Unop\"",
    "\"While\"",
    "<BoolLit>",
    "<Digit>",
    "<Letter>",
    "<IntLit>",
    "<Id>",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!\"",
  };

}
