#!/bin/sh

# Script for running miniJava compiler tests. 
# (For CS322 Language and Compiler Design, Portland State University.)
#
# Usage:
#   ./run tst/test01.s  -- test a single program 
#   ./run tst/test*.s   -- test all programs
#

for i
do
	d=`dirname $i`
	f=`basename $i .s`
	echo -n "$d/$f: "
	gcc -o $d/$f $d/$f.s lib.c
# on MacOS add following flags to previous line: -Wl,-no_pie
	$d/$f > $d/$f.out
	if [ -r $d/$f.out.ref ]; then
          diff -w $d/$f.out $d/$f.out.ref > $d/$f.out.diff; 
          if [ -s $d/$f.out.diff ]; then 
            echo "differs from ref (see $f.out.diff)"; 
          else
            echo "matches ref"; 
	    rm $d/$f.out.diff; 
          fi
	else
            echo "no ref to compare"; 
        fi
done
exit 0
